version: 2.1


orbs:
  buildevents: honeycombio/buildevents@0.1.1


executors:
  linuxgo:
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace
  catchend:
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish:
          timeout: 1

  sleep2:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID \
                    ${BUILDEVENTS_SPAN_ID} sleep -- sleep 19

  test_extra_fields:
    executor: linuxgo
    steps:
      - run: curl -q -L -o ./betesting https://268-172153261-gh.circle-artifacts.com/0/go/src/github.com/honeycombio/buildevents/artifacts/buildevents
      - run: chmod 755 ./betesting
      - run: echo 'foo=bar a=14 baz="hello kitty" cool%story=bro f %^asdf' > ./extra_fields.logfmt
      - run: echo 'export BUILDEVENT_FILE=./extra_fields.logfmt' >> $BASH_ENV
      - run: ./betesting cmd $CIRCLE_WORKFLOW_ID $(echo $CIRCLE_JOB | sha256sum | awk '{print $1}') extra -- sleep 1
      - run: ./betesting step $CIRCLE_WORKFLOW_ID $(echo $CIRCLE_JOB | sha256sum | awk '{print $1}') $(date +%s) test_extra_fields


  sleep3:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: date +%s > /tmp/start
            - run: sleep 12
            # - run: "false"
  finish:
    executor: linuxgo
    steps:
      - run: echo "all done"
workflows:
  paint:
    jobs:
      - setup
      - catchend:
          requires:
            - setup
      - sleep2:
          requires:
            - setup
      - sleep3:
          requires:
            - setup
      - finish:
          requires:
            - sleep2
            - sleep3

