version: 2.1


orbs:
  buildevents: honeycombio/buildevents@dev:ben.spanids

executors:
  linuxgo:
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace
  catchend:
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish
          # timeout: 10
  # catchend:
  #   executor: linuxgo
  #   steps:
  #     - run: |
  #         curl -q -o be https://327-172153261-gh.circle-artifacts.com/0/go/src/github.com/honeycombio/buildevents/artifacts/buildevents-linux-amd64
  #         chmod 755 ./be
  #         export BUILDEVENT_TIMEOUT=10
  #         ./be watch aoeu

  sleep2:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID \
                    ${BUILDEVENTS_SPAN_ID} sleep -- sleep 9
            - buildevents/add_context:
                field_name: subshell
                field_value: $(date "+%H:%M:%S.%6N")
                verbose: true
            - run: echo "artisize=12345" >> $BASH_ENV
            - run: echo $artisize
            - buildevents/add_context:
                field_name: shell_vars
                field_value: $artisize


  test_extra_fields:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - buildevents/add_context:
                field_name: before
                field_value: really happy before monkeys
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $(echo $CIRCLE_JOB | sha256sum | awk '{print $1}') extra -- sleep 1
            - buildevents/add_context:
                field_name: after
                field_value: "$(echo $$) "


  sleep3:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: date +%s > /tmp/start
            - run: sleep 122
            # - run: "false"
            - store_artifacts:
                path: artifacts/

  finish:
    executor: linuxgo
    steps:
      - run: echo "all done"
workflows:
  paint:
    jobs:
      - setup
      - catchend:
          requires:
            - setup
      - sleep2:
          requires:
            - setup
      # - test_extra_fields:
      #     requires:
      #       - setup
      - sleep3:
          requires:
            - setup
      - finish:
          requires:
            - sleep2
            - sleep3

