version: 2.1


orbs:
  buildevents: honeycombio/buildevents@dev:ben.update_be


executors:
  linuxgo:
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - buildevents/start_trace
  catchend:
    executor: linuxgo
    steps:
      - buildevents/watch_build_and_finish:
          timeout: 10

  sleep2:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID \
                    ${BUILDEVENTS_SPAN_ID} sleep -- sleep 19

  test_extra_fields:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - buildevents/add_context:
                field_name: before
                field_value: really happy before monkeys
            - run: buildevents cmd $CIRCLE_WORKFLOW_ID $(echo $CIRCLE_JOB | sha256sum | awk '{print $1}') extra -- sleep 1
            - buildevents/add_context:
                field_name: after
                field_value: "$(echo $$) "


  sleep3:
    executor: linuxgo
    steps:
      - buildevents/with_job_span:
          steps:
            - run: date +%s > /tmp/start
            - run: sleep 12
            # - run: "false"
  finish:
    executor: linuxgo
    steps:
      - run: echo "all done"
workflows:
  paint:
    jobs:
      - setup
      - catchend:
          requires:
            - setup
      - sleep2:
          requires:
            - setup
      - test_extra_fields:
          requires:
            - setup
      - sleep3:
          requires:
            - test_extra_fields
      - finish:
          requires:
            - sleep2
            - sleep3

