version: 2.1

executors:
  linuxgo:
    docker:
      - image: circleci/golang:1.10

jobs:
  setup:
    executor: linuxgo
    steps:
      - run: mkdir -p /tmp/be
      - run: curl -q -L -o /tmp/be/buildevents https://187-172153261-gh.circle-artifacts.com/0/go/src/github.com/honeycombio/buildevents/artifacts/buildevents
      - run: chmod 755 /tmp/be/buildevents
      - persist_to_workspace:
          root: /tmp/be
          paths:
            - buildevents
  catchend:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: /tmp/be
      - run: /tmp/be/buildevents watch $CIRCLE_WORKFLOW_ID - -
  sleep2:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: /tmp/be
      - run: date +%s > /tmp/start
      - run: /tmp/be/buildevents cmd $CIRCLE_WORKFLOW_ID \
              ${CIRCLE_JOB} sleep -- sleep 20
      - run:
          name: report_span
          command: /tmp/be/buildevents step $CIRCLE_WORKFLOW_ID \
              $CIRCLE_JOB \
              $(cat /tmp/start) sleep2
          when: always

  sleep3:
    executor: linuxgo
    steps:
      - attach_workspace:
          at: /tmp/be
      - run: date +%s > /tmp/start
      - run: sleep 15
      # - run: "false"
      - run:
          name: report_span
          command: /tmp/be/buildevents step $CIRCLE_WORKFLOW_ID \
              $CIRCLE_JOB \
              $(cat /tmp/start) sleep3
          when: always
  finish:
    executor: linuxgo
    steps:
      - run: echo "all done"

workflows:
  paint:
    jobs:
      - setup
      - catchend:
          requires:
            - setup
      - sleep2:
          requires:
            - setup
      - sleep3:
          requires:
            - setup
      - finish:
          requires:
            - sleep2
            - sleep3

